
###
GET http://localhost:8092/api/microservicio-recetas/manage/health


###
GET http://localhost:8092/api/microservicio-recetas/recetas/1

###
GET http://localhost:8092/api/microservicio-recetas/recetas


###
GET http://localhost:8092/api/microservicio-recetas/recetas/paciente/1

###
GET http://localhost:8092/api/microservicio-recetas/recetas/info-container

###
POST http://localhost:8092/api/microservicio-recetas/recetas
Content-Type: application/json

{
    "nombreGenericoMedicamentoPreescrito":"nombreGenericoMedicamentoPreescrito",
    "viaCuidadoEspecialesAdministracion":"viaCuidadoEspecialesAdministracion",
    "concentracionDosificacion":"",
    "frecuenciaAdministracion24hrs":"",
    "idMedico":1,
    "idHistoriaClinica":1
}
###
PUT http://localhost:8092/api/microservicio-recetas/recetas/6
Content-Type: application/json

{
    "nombreGenericoMedicamentoPreescrito":"actualizado",
    "viaCuidadoEspecialesAdministracion":"",
    "concentracionDosificacion":"",
    "frecuenciaAdministracion24hrs":"",
    "idMedico":2,
    "idHistoriaClinica":2
}
